In [1]:
import pandas as pd

In [3]:
# conjunto de datos

datos = {
		"usuario" : ["Ana", "Luis", "Martha", "Carolina", "Sofia", "Pedro", "Elena", "Diego"],
	
		"edad" : [22 , 35 , 28 , 40 , 19 , 31 , 26 , 45],
	
		"ciudad" : ["CDMX","Monterrey","Guadalajara","Puebla","Cancun","Merida","Tijuana","Toluca"],
			
		"compras_realizadas" : [5 , 12 , 3 , 29 , 1 , 7 , 4 , 15],
		
		"activo" : [True, False, True, True , False , True , False, True],
		
		"fecha_registro" : ["2026-01-10", "2026-10-23", "2012-12-21" , "2023-07-11", "2014-02-12", "2021-01-30", "2022-08-18" , "2024-01-12"]
}

In [4]:
#convertir a dataframe
df = pd.DataFrame(datos)
print(df)

    usuario  edad       ciudad  compras_realizadas  activo fecha_registro
0       Ana    22         CDMX                   5    True     2026-01-10
1      Luis    35    Monterrey                  12   False     2026-10-23
2    Martha    28  Guadalajara                   3    True     2012-12-21
3  Carolina    40       Puebla                  29    True     2023-07-11
4     Sofia    19       Cancun                   1   False     2014-02-12
5     Pedro    31       Merida                   7    True     2021-01-30
6     Elena    26      Tijuana                   4   False     2022-08-18
7     Diego    45       Toluca                  15    True     2024-01-12

In [5]:
#mostrar los primeros 5
df.head()

    usuario  edad       ciudad  compras_realizadas  activo fecha_registro
0       Ana    22         CDMX                   5    True     2026-01-10
1      Luis    35    Monterrey                  12   False     2026-10-23
2    Martha    28  Guadalajara                   3    True     2012-12-21
3  Carolina    40       Puebla                  29    True     2023-07-11
4     Sofia    19       Cancun                   1   False     2014-02-12

In [6]:
# o lo especificado
df.head(1)

  usuario  edad ciudad  compras_realizadas  activo fecha_registro
0     Ana    22   CDMX                   5    True     2026-01-10

In [7]:
# libreria de random
import random

In [10]:
#crear un data frame con 1,000,000 de registros

cantidad = 100000000

In [8]:
#datos aleatorios
nombres = ["Ana", "Luis", "Martha", "Carolina", "Sofia", "Pedro", "Elena", "Diego"]
ciudades = ["CDMX","Monterrey","Guadalajara","Puebla","Cancun","Merida","Tijuana","Toluca"]
categorias = ["Tecnologias" , "ropa" ,"hogar" ,"herramientas" ,"consolas" ,"deportes" ,"calzado" ,"jardineria" ,]

In [13]:
# creacion del DataFrame

dfMillon = pd.DataFrame({
	"nombre" : [ random.choice(nombres) for _ in range(cantidad)],
	"edad" : [ random.randint(18,70) for _ in range(cantidad)],
	"salario" : [ round(random.uniform(5000,50000),2) for _ in range(cantidad)],
	"activo" : [ random.choice([True,False]) for _ in range(cantidad)],
	"categorias" : [ random.choice(categorias) for _ in range(cantidad)],
	"ciudades" : [ random.choice(ciudades) for _ in range(cantidad)],
	"anio_registro" : [ random.randint(2020,2026) for _ in range(cantidad)],
})

In [14]:
dfMillon.shape

(1000000, 7)

In [15]:
#para ver q tipo de dato lo definio
dfMillon.dtypes

nombre               str
edad               int64
salario          float64
activo              bool
categorias           str
ciudades             str
anio_registro      int64
dtype: object

In [16]:
dfMillon.memory_usage(deep=True)

Index                 132
nombre           62125057
edad              8000000
salario           8000000
activo            1000000
categorias       65125841
ciudades         63877645
anio_registro     8000000
dtype: int64

In [17]:
# para ver el peso de todo el dataset en mb
dfMillon.memory_usage(deep=True).sum()/1024**2

np.float64(206.11636638641357)